# Information for configurating script and converting EDDs

# Please enter all necessary information below before running scripts


project info: 
  project number: "19-07202-006" # USE PROJ # FROM ESDAT
  project name:   "Bellevue Streams" # USE PROJ NAME FROM KCEL EDD FILENAME