# Information for configurating script and converting EDDs

# Please enter all necessary information below before running scripts


project_info: 
  project_number: "19-07202-000" # USE PROJ # FROM ESDAT
  project_name:   "Bellevue Utlilities Monitoring" # USE PROJ NAME FROM ESDAT
  