# Information for configurating script and converting EDDs

# Please enter all necessary information below before running scripts


project_info: 
  project_number: "19-07202-006" # USE PROJ # FROM ESDAT
  project_name:   "Bellevue Streams" # USE PROJ NAME FROM KCEL EDD FILENAME