# Information for configurating script and converting EDDs

# Please enter all necessary information below before running scripts


project_info: 
  project_number: "21-07565-001" # USE PROJ # FROM ESDAT
  project_name:   "PBOOM: Park Place" # USE PROJ NAME FROM ESDAT
  project_site:   "Park-Place" # site from ESdat
  sample_matrix:  "Water"