# Information for configurating script and converting EDDs

# Please enter all necessary information below before running scripts


project_info:
  project_number: "23-08229-000" # USE PROJ # FROM ESDAT
  project_name:   "PBOOM: Park Place" # USE PROJ NAME FROM ESDAT
  project_site:   "Bellingham-Misc" # site from ESdat
  sample_matrix:  "Water"
